import React, { useMemo, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Link, Trash2, RefreshCw, AlertTriangle } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";

function normalize(s) { return (s || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[.,]/g, " ").replace(/\s+/g, " ").trim(); }

export default function NutritionRepairPanel({ assessments, players, onReload }) {
  const [selected, setSelected] = useState({}); const [busy, setBusy] = useState(null); const { toast } = useToast();
  const playerMap = useMemo(() => Object.fromEntries(players.map(p => [p.id, p.full_name || `${p.first_name || ""} ${p.last_name || ""}`.trim()])), [players]);
  const unlinked = assessments.filter(a => !a.linked || !a.player_id).slice(0, 40);
  const orphan = assessments.filter(a => a.player_id && !playerMap[a.player_id]);
  const incomplete = assessments.filter(a => !a.fecha || !a.player_name_original || a.peso === undefined);
  const dupGroups = Object.values(assessments.reduce((acc, a) => { const k = a.nutrition_assessment_key || `${a.player_id}|${a.fecha}|${a.tipo_medicion}`; acc[k] = acc[k] || []; acc[k].push(a); return acc; }, {})).filter(g => g.length > 1);
  async function linkAssessment(a) { const pid = selected[a.id]; if (!pid) return; setBusy(a.id); const playerName = playerMap[pid]; const key = `${pid}|${a.fecha}|${normalize(a.tipo_medicion || "Antropometría")}`; await base44.entities.NutritionAssessment.update(a.id, { player_id: pid, linked: true, nutrition_assessment_key: key, updated_at: new Date().toISOString() }); await base44.entities.PlayerAlias.create({ player_id: pid, player_name: playerName, alias_name: a.player_name_original, normalized_alias: normalize(a.player_name_original), source: "Nutrición", confidence_score: 1 }); toast({ title: "Jugador vinculado y alias guardado" }); setBusy(null); onReload(); }
  async function deleteDuplicate(group) { const sorted = [...group].sort((a, b) => (b.updated_at || b.updated_date || "").localeCompare(a.updated_at || a.updated_date || "")); setBusy(group[0].nutrition_assessment_key); for (const item of sorted.slice(1)) await base44.entities.NutritionAssessment.delete(item.id); toast({ title: `${sorted.length - 1} duplicados eliminados` }); setBusy(null); onReload(); }
  return <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 space-y-5"><div><h3 className="text-white font-semibold flex items-center gap-2"><RefreshCw size={15} className="text-amber-400" /> Reparar sincronización nutricional</h3><p className="text-xs text-zinc-500 mt-1">Detecta sin vincular, duplicados, huérfanos e incompletos. La nutrición nunca crea jugadores nuevos.</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs"><div className="bg-zinc-800 rounded-lg p-3"><b className="text-amber-300">{unlinked.length}</b><br />Sin vincular</div><div className="bg-zinc-800 rounded-lg p-3"><b className="text-red-300">{dupGroups.length}</b><br />Grupos duplicados</div><div className="bg-zinc-800 rounded-lg p-3"><b className="text-pink-300">{orphan.length}</b><br />Huérfanos</div><div className="bg-zinc-800 rounded-lg p-3"><b className="text-blue-300">{incomplete.length}</b><br />Incompletos</div></div>{unlinked.length > 0 && <div className="space-y-2"><p className="text-xs text-zinc-400 uppercase font-semibold">Jugadores de nutrición sin vincular</p>{unlinked.map(a => <div key={a.id} className="grid grid-cols-1 md:grid-cols-[1fr_220px_auto] gap-2 items-center bg-zinc-800/50 border border-zinc-700 rounded-lg p-3"><div><p className="text-sm text-white">{a.player_name_original}</p><p className="text-xs text-zinc-500">{a.fecha} · {a.categoria_division || "Sin categoría"}</p></div><select value={selected[a.id] || ""} onChange={e => setSelected(s => ({ ...s, [a.id]: e.target.value }))} className="bg-zinc-900 border border-zinc-700 rounded-lg px-2 py-2 text-xs text-white"><option value="">Vincular con...</option>{players.map(p => <option key={p.id} value={p.id}>{playerMap[p.id]}</option>)}</select><button onClick={() => linkAssessment(a)} disabled={!selected[a.id] || busy === a.id} className="flex items-center gap-1 px-3 py-2 bg-white text-zinc-900 rounded-lg text-xs disabled:opacity-50"><Link size={12} /> Vincular</button></div>)}</div>}{dupGroups.length > 0 && <div className="space-y-2"><p className="text-xs text-zinc-400 uppercase font-semibold">Mediciones duplicadas</p>{dupGroups.slice(0, 20).map(g => <div key={g[0].nutrition_assessment_key} className="flex items-center justify-between gap-3 bg-red-500/10 border border-red-500/20 rounded-lg p-3"><div><p className="text-sm text-red-200 flex items-center gap-2"><AlertTriangle size={13} /> {playerMap[g[0].player_id] || g[0].player_name_original}</p><p className="text-xs text-red-200/60">{g.length} registros · {g[0].fecha}</p></div><button onClick={() => deleteDuplicate(g)} disabled={!!busy} className="flex items-center gap-1 px-3 py-2 bg-red-500/20 text-red-200 border border-red-500/30 rounded-lg text-xs"><Trash2 size={12} /> Eliminar duplicados</button></div>)}</div>}</div>;
}