import React, { useMemo } from "react";
import { BarChart, Bar, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

function avg(rows, field) { const nums = rows.map(r => Number(r[field])).filter(Number.isFinite); return nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0; }

export default function NutritionCharts({ assessments }) {
  const byMonth = useMemo(() => Object.values(assessments.reduce((acc, a) => { const k = (a.fecha || "").slice(0, 7) || "Sin fecha"; acc[k] = acc[k] || { month: k, rows: [] }; acc[k].rows.push(a); return acc; }, {})).sort((a, b) => a.month.localeCompare(b.month)).slice(-6).map(g => ({ month: g.month.slice(5) || "—", peso: +avg(g.rows, "peso").toFixed(1), sum6p: +avg(g.rows, "sumatoria_6p").toFixed(1), grasa: +avg(g.rows, "porcentaje_grasa").toFixed(1), kgmm: +avg(g.rows, "kg_masa_muscular").toFixed(1) })), [assessments]);
  const latestByPlayer = useMemo(() => { const map = new Map(); assessments.filter(a => a.linked && a.player_id).forEach(a => { if (!map.has(a.player_id) || (a.fecha || "") > (map.get(a.player_id).fecha || "")) map.set(a.player_id, a); }); return [...map.values()]; }, [assessments]);
  const fatDist = [{ name: "< 10%", value: latestByPlayer.filter(a => Number(a.porcentaje_grasa) < 10).length, color: "#16a34a" }, { name: "10 - 14%", value: latestByPlayer.filter(a => Number(a.porcentaje_grasa) >= 10 && Number(a.porcentaje_grasa) < 14).length, color: "#facc15" }, { name: "14 - 18%", value: latestByPlayer.filter(a => Number(a.porcentaje_grasa) >= 14 && Number(a.porcentaje_grasa) < 18).length, color: "#fb923c" }, { name: "> 18%", value: latestByPlayer.filter(a => Number(a.porcentaje_grasa) >= 18).length, color: "#ef4444" }];
  const sumDist = ["0-20", "20-30", "30-40", "40-50", "50-60", "60+"].map(label => ({ label, value: latestByPlayer.filter(a => { const v = Number(a.sumatoria_6p); if (label === "60+") return v >= 60; const [min, max] = label.split("-").map(Number); return v >= min && v < max; }).length }));
  return <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="lg:col-span-2 bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><h3 className="font-bold text-slate-900 mb-4">Evolución promedio del plantel</h3><div className="h-72"><ResponsiveContainer><LineChart data={byMonth}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Legend /><Line type="monotone" dataKey="peso" name="Peso (kg)" stroke="#16a34a" strokeWidth={2} /><Line type="monotone" dataKey="sum6p" name="Sum. 6P" stroke="#2563eb" strokeWidth={2} /><Line type="monotone" dataKey="grasa" name="% Grasa" stroke="#f59e0b" strokeWidth={2} /><Line type="monotone" dataKey="kgmm" name="Kg MM" stroke="#8b5cf6" strokeWidth={2} /></LineChart></ResponsiveContainer></div></div><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><h3 className="font-bold text-slate-900 mb-4">Distribución de % Grasa</h3><div className="h-56"><ResponsiveContainer><PieChart><Pie data={fatDist} dataKey="value" innerRadius={55} outerRadius={90}>{fatDist.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="space-y-2">{fatDist.map(item => <div key={item.name} className="flex justify-between text-xs"><span className="flex items-center gap-2"><i className="w-2 h-2 rounded-full" style={{ background: item.color }} />{item.name}</span><b>{item.value}</b></div>)}</div></div><div className="lg:col-span-3 bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><h3 className="font-bold text-slate-900 mb-4">Distribución de Sumatoria 6P</h3><div className="h-64"><ResponsiveContainer><BarChart data={sumDist}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="value" fill="#65c18c" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></div></div>;
}