import React from "react";
import moment from "moment";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import { Scale, TrendingUp, ArrowUpRight, ArrowDownRight } from "lucide-react";

const metrics = [
  ["peso", "Peso", "kg", "#60a5fa"], ["sumatoria_6p", "Sumatoria 6P", "", "#fb923c"], ["porcentaje_grasa", "% grasa", "%", "#f472b6"], ["kg_grasa", "KG grasa", "kg", "#f87171"], ["kg_masa_muscular", "KG masa muscular", "kg", "#a78bfa"], ["imo", "IMO", "", "#34d399"],
];
function fmt(v, unit = "") { return v !== undefined && v !== null && v !== "" ? `${Number(v).toFixed(1)}${unit ? ` ${unit}` : ""}` : "—"; }
function MiniChart({ data, metric }) { const [key, label, unit, color] = metric; return <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-3"><p className="text-xs text-zinc-400 font-semibold mb-2">{label}</p><div className="h-32"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#27272a" strokeDasharray="3 3" /><XAxis dataKey="label" tick={{ fill: "#71717a", fontSize: 10 }} /><YAxis tick={{ fill: "#71717a", fontSize: 10 }} width={30} /><Tooltip contentStyle={{ background: "#18181b", border: "1px solid #3f3f46", borderRadius: 10, color: "#fff" }} formatter={(v) => [`${v}${unit ? ` ${unit}` : ""}`, label]} /><Line type="monotone" dataKey={key} stroke={color} strokeWidth={2} dot={{ r: 2 }} connectNulls /></LineChart></ResponsiveContainer></div></div>; }
export default function PlayerNutritionTab({ assessments = [] }) {
  if (!assessments.length) return <div className="text-center py-10 text-zinc-600 text-sm">Sin mediciones nutricionales</div>;
  const sorted = [...assessments].sort((a, b) => (a.fecha || "").localeCompare(b.fecha || ""));
  const latest = sorted[sorted.length - 1], previous = sorted[sorted.length - 2];
  const chartData = sorted.map(a => ({ ...a, label: a.fecha ? moment(a.fecha).format("DD/MM") : "—" }));
  return <div className="space-y-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4"><Scale size={15} className="text-blue-400" /><p className="text-xl font-bold text-white mt-2">{fmt(latest.peso, "kg")}</p><p className="text-xs text-zinc-500">Último peso</p></div><div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4"><TrendingUp size={15} className="text-orange-400" /><p className="text-xl font-bold text-white mt-2">{fmt(latest.sumatoria_6p)}</p><p className="text-xs text-zinc-500">Última Sum. 6P</p></div><div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4"><p className="text-xl font-bold text-pink-400">{fmt(latest.porcentaje_grasa, "%")}</p><p className="text-xs text-zinc-500">Último % grasa</p></div><div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4"><p className="text-xl font-bold text-purple-400">{fmt(latest.kg_masa_muscular, "kg")}</p><p className="text-xs text-zinc-500">Último KG MM</p></div></div>{previous && <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4"><p className="text-xs text-zinc-500 mb-2">Comparación contra medición anterior · {moment(previous.fecha).format("DD/MM/YYYY")} → {moment(latest.fecha).format("DD/MM/YYYY")}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">{["peso", "sumatoria_6p", "porcentaje_grasa", "kg_masa_muscular"].map(k => { const diff = Number(latest[k] || 0) - Number(previous[k] || 0); return <div key={k} className="flex items-center gap-1 text-zinc-300">{diff >= 0 ? <ArrowUpRight size={12} className="text-amber-400" /> : <ArrowDownRight size={12} className="text-emerald-400" />} {k}: {diff.toFixed(1)}</div>; })}</div></div>}<div className="grid grid-cols-1 md:grid-cols-2 gap-3">{metrics.map(m => <MiniChart key={m[0]} data={chartData} metric={m} />)}</div></div>;
}