import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Binoculars, CalendarCheck, ClipboardList, GitCompareArrows, ListChecks, Loader2, Plus, Search, Shield, SlidersHorizontal, Target, UsersRound } from "lucide-react";
import { scoutingOverview } from "@/lib/scoutingApi";
import ProspectFormModal from "@/components/scouting/ProspectFormModal";
import RecruitmentNeedModal from "@/components/scouting/RecruitmentNeedModal";
import ScoutingAssignmentModal from "@/components/scouting/ScoutingAssignmentModal";
import ScoutingReportModal from "@/components/scouting/ScoutingReportModal";
import ProspectDetailModal from "@/components/scouting/ProspectDetailModal";
import RoleProfileModal from "@/components/scouting/RoleProfileModal";
import WatchlistModal from "@/components/scouting/WatchlistModal";
import ScoutingComparisonTab from "@/components/scouting/ScoutingComparisonTab";
import ShadowSquadTab from "@/components/scouting/ShadowSquadTab";
import RecruitmentMeetingsTab from "@/components/scouting/RecruitmentMeetingsTab";
import { ASSIGNMENT_LABEL, HORIZON_LABEL, PIPELINE_STAGES, PRIORITY_LABEL, RECOMMENDATION_LABEL, STAGE_LABEL, fmtDate, fmtMoney, prospectAge } from "@/components/scouting/scoutingConstants";

const TABS=[
 {id:"pipeline",label:"Pipeline",icon:ListChecks},{id:"comparison",label:"Comparador",icon:GitCompareArrows},{id:"shadow",label:"Shadow Squad",icon:Shield},{id:"meetings",label:"Recruitment Meetings",icon:CalendarCheck},{id:"prospects",label:"Prospectos",icon:UsersRound},{id:"needs",label:"Necesidades",icon:Target},{id:"assignments",label:"Asignaciones",icon:ClipboardList},{id:"watchlists",label:"Watchlists",icon:Binoculars},{id:"roles",label:"Perfiles de rol",icon:SlidersHorizontal},
];
function Card({label,value,sub,accent="text-white"}){return <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p><p className={`text-2xl font-bold mt-1 ${accent}`}>{value}</p>{sub&&<p className="text-[11px] text-zinc-600 mt-1">{sub}</p>}</div>}
function Badge({children,className=""}){return <span className={`inline-flex px-2 py-1 rounded-full border text-[10px] font-semibold ${className}`}>{children}</span>}

export default function Scouting(){
 const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[tab,setTab]=useState("pipeline");const[search,setSearch]=useState("");const[stageFilter,setStageFilter]=useState("");
 const[selectedProspect,setSelectedProspect]=useState(null);const[editProspect,setEditProspect]=useState(null);const[editNeed,setEditNeed]=useState(null);const[editRole,setEditRole]=useState(null);const[showProspect,setShowProspect]=useState(false);const[showNeed,setShowNeed]=useState(false);const[showAssignment,setShowAssignment]=useState(false);const[assignmentProspect,setAssignmentProspect]=useState(null);const[showReport,setShowReport]=useState(false);const[reportProspect,setReportProspect]=useState(null);const[showRole,setShowRole]=useState(false);const[showWatchlist,setShowWatchlist]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await scoutingOverview())}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const prospects=data?.prospects||[],needs=data?.needs||[],assignments=data?.assignments||[],reports=data?.reports||[],watchlists=data?.watchlists||[],items=data?.watchlist_items||[],roles=data?.role_profiles||[],shadowPlans=data?.shadow_plans||[],shadowSlots=data?.shadow_slots||[],meetings=data?.meetings||[],decisions=data?.decisions||[];
 const reportByProspect=useMemo(()=>{const map=new Map();reports.forEach(r=>{if(!map.has(r.prospect_id))map.set(r.prospect_id,[]);map.get(r.prospect_id).push(r)});return map},[reports]);
 const latestReport=useMemo(()=>new Map([...reportByProspect.entries()].map(([id,rs])=>[id,[...rs].sort((a,b)=>String(b.observation_date||"").localeCompare(String(a.observation_date||"")))[0]])),[reportByProspect]);
 const activeProspects=prospects.filter(p=>p.status!=="archived"&&p.pipeline_stage!=="discarded");const openNeeds=needs.filter(n=>!["filled","cancelled"].includes(n.status));const pendingAssignments=assignments.filter(a=>["pending","in_progress"].includes(a.status));
 const filteredProspects=prospects.filter(p=>{if(stageFilter&&p.pipeline_stage!==stageFilter)return false;if(search&&!`${p.full_name} ${p.current_club_name} ${p.position} ${p.nationality}`.toLowerCase().includes(search.toLowerCase()))return false;return true});
 const canCreate=data?.capabilities?.can_create;const canEdit=data?.capabilities?.can_edit;
 function refresh(){load()}
 function openEditProspect(p){setSelectedProspect(null);setEditProspect(p);setShowProspect(true)}
 function openReport(id){setReportProspect(id);setShowReport(true)}
 function openAssignment(id=null){setAssignmentProspect(id);setShowAssignment(true)}
 if(loading&&!data)return <div className="min-h-[60vh] flex items-center justify-center"><Loader2 className="animate-spin text-zinc-500"/></div>;
 return <div className="p-4 sm:p-6 max-w-[1600px] mx-auto space-y-5">
  <div className="flex items-start justify-between gap-4 flex-wrap"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl bg-amber-500/10 border border-amber-500/25 flex items-center justify-center"><Binoculars size={23} className="text-amber-400"/></div><div><h1 className="text-2xl font-bold text-white">Scouting & Recruitment</h1><p className="text-sm text-zinc-500 mt-0.5">Necesidad → observación → evidencia → decisión → mercado</p></div></div><div className="flex gap-2 flex-wrap">{canCreate&&<><button onClick={()=>{setEditNeed(null);setShowNeed(true)}} className="px-3.5 py-2 rounded-lg border border-zinc-700 bg-zinc-900 text-zinc-200 text-sm font-semibold flex items-center gap-1.5"><Target size={14}/> Nueva necesidad</button><button onClick={()=>{setEditProspect(null);setShowProspect(true)}} className="px-3.5 py-2 rounded-lg bg-white text-zinc-950 text-sm font-bold flex items-center gap-1.5"><Plus size={14}/> Nuevo prospecto</button></>}</div></div>
  {error&&<div className="p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-sm text-red-300">{error}</div>}
  <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3"><Card label="Prospectos activos" value={activeProspects.length}/><Card label="Shortlist" value={prospects.filter(p=>p.pipeline_stage==="shortlist").length} accent="text-blue-300"/><Card label="Prioridad" value={prospects.filter(p=>p.pipeline_stage==="priority").length} accent="text-amber-300"/><Card label="Necesidades abiertas" value={openNeeds.length}/><Card label="Asignaciones pendientes" value={pendingAssignments.length} accent={pendingAssignments.length?"text-violet-300":"text-white"}/><Card label="Informes" value={reports.length} sub="historial acumulado"/></div>
  <div className="flex items-center gap-1 overflow-x-auto border-b border-zinc-800">{TABS.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 whitespace-nowrap ${tab===t.id?"border-amber-400 text-amber-300":"border-transparent text-zinc-500 hover:text-white"}`}><t.icon size={15}/>{t.label}</button>)}</div>
  {tab==="pipeline"&&<Pipeline prospects={prospects} latestReport={latestReport} onSelect={setSelectedProspect}/>} 
  {tab==="comparison"&&<ScoutingComparisonTab prospects={prospects} players={data?.players||[]}/>} 
  {tab==="shadow"&&<ShadowSquadTab plans={shadowPlans} slots={shadowSlots} prospects={prospects} players={data?.players||[]} roles={roles} needs={needs} squads={data?.squads||[]} canCreate={canCreate} canEdit={canEdit} onChanged={refresh}/>} 
  {tab==="meetings"&&<RecruitmentMeetingsTab meetings={meetings} decisions={decisions} prospects={prospects} needs={needs} staff={data?.staff||[]} squads={data?.squads||[]} canCreate={canCreate} canEdit={canEdit} onChanged={refresh}/>} 
  {tab==="prospects"&&<section className="space-y-3"><div className="flex gap-2 flex-wrap"><div className="relative flex-1 min-w-56"><Search size={14} className="absolute left-3 top-2.5 text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Jugador, club, posición, nacionalidad..." className="w-full bg-zinc-900 border border-zinc-800 rounded-lg pl-9 pr-3 py-2 text-sm text-white"/></div><select value={stageFilter} onChange={e=>setStageFilter(e.target.value)} className="bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2 text-sm text-zinc-300"><option value="">Todas las etapas</option>{PIPELINE_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></div><ProspectTable prospects={filteredProspects} latestReport={latestReport} reportByProspect={reportByProspect} onSelect={setSelectedProspect}/></section>}
  {tab==="needs"&&<NeedsView needs={needs} roles={roles} prospects={prospects} onEdit={n=>{setEditNeed(n);setShowNeed(true)}} canEdit={canEdit}/>} 
  {tab==="assignments"&&<AssignmentsView assignments={assignments} prospects={prospects} onNew={()=>openAssignment()} canCreate={canCreate}/>} 
  {tab==="watchlists"&&<WatchlistsView watchlists={watchlists} items={items} prospects={prospects} onSelect={setSelectedProspect} onNew={()=>setShowWatchlist(true)} canCreate={canCreate}/>} 
  {tab==="roles"&&<RoleProfilesView roles={roles} onEdit={r=>{setEditRole(r);setShowRole(true)}} onNew={()=>{setEditRole(null);setShowRole(true)}} canCreate={canCreate} canEdit={canEdit}/>} 

  {selectedProspect&&<ProspectDetailModal prospectId={selectedProspect} onClose={()=>setSelectedProspect(null)} onEdit={openEditProspect} onReport={openReport} onAssignment={openAssignment} onChanged={refresh}/>} 
  {showProspect&&<ProspectFormModal prospect={editProspect} roleProfiles={roles} needs={needs} onClose={()=>{setShowProspect(false);setEditProspect(null)}} onSaved={refresh}/>} 
  {showNeed&&<RecruitmentNeedModal need={editNeed} squads={data?.squads||[]} players={data?.players||[]} roleProfiles={roles} staff={data?.staff||[]} onClose={()=>{setShowNeed(false);setEditNeed(null)}} onSaved={refresh}/>} 
  {showAssignment&&<ScoutingAssignmentModal prospectId={assignmentProspect} prospects={prospects} needs={needs} staff={data?.staff||[]} onClose={()=>{setShowAssignment(false);setAssignmentProspect(null)}} onSaved={refresh}/>} 
  {showReport&&<ScoutingReportModal prospectId={reportProspect} prospects={prospects} needs={needs} assignments={assignments} roleProfiles={roles} onClose={()=>{setShowReport(false);setReportProspect(null)}} onSaved={refresh}/>} 
  {showRole&&<RoleProfileModal profile={editRole} onClose={()=>{setShowRole(false);setEditRole(null)}} onSaved={refresh}/>} 
  {showWatchlist&&<WatchlistModal needs={needs} squads={data?.squads||[]} onClose={()=>setShowWatchlist(false)} onSaved={refresh}/>} 
 </div>
}

function Pipeline({prospects,latestReport,onSelect}){const visible=PIPELINE_STAGES.filter(s=>!["signed","discarded"].includes(s.id));return <div className="overflow-x-auto pb-2"><div className="grid gap-3 min-w-[1450px]" style={{gridTemplateColumns:`repeat(${visible.length},minmax(190px,1fr))`}}>{visible.map(stage=>{const rows=prospects.filter(p=>p.pipeline_stage===stage.id&&p.status!=="archived");return <div key={stage.id} className="rounded-xl border border-zinc-800 bg-zinc-950/40 overflow-hidden"><div className="px-3 py-2.5 bg-zinc-900 border-b border-zinc-800 flex items-center justify-between"><span className="text-xs font-bold text-zinc-300">{stage.label}</span><span className="text-[10px] text-zinc-600">{rows.length}</span></div><div className="p-2 space-y-2 min-h-36">{rows.map(p=><ProspectCard key={p.id} p={p} report={latestReport.get(p.id)} onClick={()=>onSelect(p.id)}/>)}{!rows.length&&<p className="text-[11px] text-zinc-700 text-center pt-6">Sin jugadores</p>}</div></div>})}</div></div>}
function ProspectCard({p,report,onClick}){return <button onClick={onClick} className="w-full text-left rounded-lg border border-zinc-800 bg-zinc-900 p-3 hover:border-zinc-600 transition-colors"><div className="flex gap-2 items-center"><div className="w-8 h-8 rounded-full bg-zinc-800 flex items-center justify-center text-xs font-bold text-zinc-400 shrink-0">{p.full_name?.[0]}</div><div className="min-w-0"><p className="text-xs font-bold text-white truncate">{p.full_name}</p><p className="text-[10px] text-zinc-600 truncate">{p.position||"—"} · {p.current_club_name||"Sin club"}</p></div></div>{report&&<div className="mt-2 flex items-center justify-between"><span className="text-[9px] text-zinc-600">{RECOMMENDATION_LABEL[report.recommendation]||report.recommendation}</span>{report.fit_score!=null&&<span className="text-[10px] font-bold text-zinc-300">{Math.round(report.fit_score)}%</span>}</div>}</button>}
function ProspectTable({prospects,latestReport,reportByProspect,onSelect}){return <div className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-x-auto"><table className="w-full text-xs min-w-[900px]"><thead><tr className="bg-zinc-950 text-zinc-600"><th className="text-left p-3">Jugador</th><th className="text-left p-3">Etapa</th><th className="text-left p-3">Club</th><th className="text-left p-3">Posición</th><th className="text-center p-3">Edad</th><th className="text-right p-3">Valor</th><th className="text-center p-3">Informes</th><th className="text-left p-3">Última lectura</th></tr></thead><tbody>{prospects.map(p=>{const r=latestReport.get(p.id);return <tr key={p.id} onClick={()=>onSelect(p.id)} className="border-t border-zinc-800/70 hover:bg-zinc-800/40 cursor-pointer"><td className="p-3"><p className="text-white font-semibold">{p.full_name}</p><p className="text-[10px] text-zinc-600">{p.nationality||"—"}</p></td><td className="p-3"><Badge className="border-zinc-700 text-zinc-300">{STAGE_LABEL[p.pipeline_stage]||p.pipeline_stage}</Badge></td><td className="p-3 text-zinc-300">{p.current_club_name||"—"}</td><td className="p-3 text-zinc-300">{p.position||"—"}</td><td className="p-3 text-center text-zinc-400">{prospectAge(p.birth_date)??"—"}</td><td className="p-3 text-right text-zinc-300">{fmtMoney(p.market_value_estimate,p.market_value_currency)}</td><td className="p-3 text-center text-zinc-400">{reportByProspect.get(p.id)?.length||0}</td><td className="p-3 text-zinc-400">{r?RECOMMENDATION_LABEL[r.recommendation]:"Sin informe"}</td></tr>})}{!prospects.length&&<tr><td colSpan="8" className="p-10 text-center text-zinc-600">Todavía no hay prospectos.</td></tr>}</tbody></table></div>}
function NeedsView({needs,roles,prospects,onEdit,canEdit}){const roleMap=new Map(roles.map(r=>[r.id,r]));return <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{needs.map(n=><div key={n.id} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-bold text-white">{n.title}</p><p className="text-xs text-zinc-600 mt-1">{n.squad_name||"Institucional"} · {HORIZON_LABEL[n.time_horizon]||n.time_horizon}</p></div><Badge className={n.priority==="critical"?"border-red-500/30 text-red-300":n.priority==="high"?"border-amber-500/30 text-amber-300":"border-zinc-700 text-zinc-400"}>{PRIORITY_LABEL[n.priority]||n.priority}</Badge></div>{roleMap.get(n.role_profile_id)&&<p className="text-xs text-blue-300 mt-3">Rol: {roleMap.get(n.role_profile_id).name}</p>}<p className="text-xs text-zinc-400 mt-3 min-h-8">{n.reason||"Sin motivo documentado"}</p><div className="grid grid-cols-2 gap-2 mt-3"><div className="rounded-lg bg-zinc-950 p-2"><p className="text-[9px] text-zinc-600">Candidatos</p><p className="text-sm font-bold text-white">{(n.prospect_ids||[]).filter(id=>prospects.some(p=>p.id===id)).length}</p></div><div className="rounded-lg bg-zinc-950 p-2"><p className="text-[9px] text-zinc-600">Presupuesto máx.</p><p className="text-xs font-bold text-white">{fmtMoney(n.budget_max,n.budget_currency)}</p></div></div><div className="flex items-center justify-between mt-3"><Badge className="border-zinc-700 text-zinc-400">{n.status}</Badge>{canEdit&&<button onClick={()=>onEdit(n)} className="text-xs text-zinc-500 hover:text-white">Editar</button>}</div></div>)}{!needs.length&&<Empty text="Creá una necesidad antes de buscar candidatos. Eso evita que el scouting se convierta en una colección de nombres."/>}</div>}
function AssignmentsView({assignments,prospects,onNew,canCreate}){const pm=new Map(prospects.map(p=>[p.id,p]));return <div className="space-y-3">{canCreate&&<div className="flex justify-end"><button onClick={onNew} className="px-3 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold flex items-center gap-1"><Plus size={13}/> Asignación</button></div>}<div className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-x-auto"><table className="w-full text-xs min-w-[850px]"><thead><tr className="bg-zinc-950 text-zinc-600"><th className="p-3 text-left">Prospecto</th><th className="p-3 text-left">Responsable</th><th className="p-3 text-left">Tipo</th><th className="p-3 text-left">Objetivo</th><th className="p-3 text-left">Vence</th><th className="p-3 text-left">Estado</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id} className="border-t border-zinc-800"><td className="p-3 text-white font-semibold">{pm.get(a.prospect_id)?.full_name||"Prospecto"}</td><td className="p-3 text-zinc-300">{a.assigned_to_name||"—"}</td><td className="p-3 text-zinc-400">{ASSIGNMENT_LABEL[a.assignment_type]||a.assignment_type}</td><td className="p-3 text-zinc-400 max-w-xs truncate">{a.instructions||a.match_label||"—"}</td><td className="p-3 text-zinc-400">{fmtDate(a.due_date)}</td><td className="p-3"><Badge className={a.status==="completed"?"border-emerald-500/30 text-emerald-300":"border-zinc-700 text-zinc-400"}>{a.status}</Badge></td></tr>)}{!assignments.length&&<tr><td colSpan="6" className="p-10 text-center text-zinc-600">Sin asignaciones.</td></tr>}</tbody></table></div></div>}
function WatchlistsView({watchlists,items,prospects,onSelect,onNew,canCreate}){const pm=new Map(prospects.map(p=>[p.id,p]));return <div className="space-y-3">{canCreate&&<div className="flex justify-end"><button onClick={onNew} className="px-3 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold flex items-center gap-1"><Plus size={13}/> Nueva lista</button></div>}<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{watchlists.map(w=>{const wi=items.filter(i=>i.watchlist_id===w.id);return <div key={w.id} className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-hidden"><div className="p-4 border-b border-zinc-800"><div className="flex items-center justify-between"><p className="text-sm font-bold text-white">{w.name}</p><Badge className="border-zinc-700 text-zinc-400">{w.watchlist_type}</Badge></div><p className="text-xs text-zinc-600 mt-1">{w.description||"Sin descripción"}</p></div><div className="p-2 space-y-1 min-h-24">{wi.map(i=>{const p=pm.get(i.prospect_id);return p?<button key={i.id} onClick={()=>onSelect(p.id)} className="w-full flex items-center justify-between p-2 rounded-lg hover:bg-zinc-800 text-left"><span className="text-xs text-zinc-300">{p.full_name}</span><span className="text-[10px] text-zinc-600">{p.current_club_name||p.position||"—"}</span></button>:null})}{!wi.length&&<p className="text-xs text-zinc-700 text-center py-5">Lista vacía</p>}</div></div>})}</div></div>}
function RoleProfilesView({roles,onEdit,onNew,canCreate,canEdit}){return <div className="space-y-3">{canCreate&&<div className="flex justify-end"><button onClick={onNew} className="px-3 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold flex items-center gap-1"><Plus size={13}/> Perfil de rol</button></div>}<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{roles.map(r=>{const criteria=[...(r.technical_criteria||[]),...(r.tactical_criteria||[]),...(r.physical_criteria||[]),...(r.mental_criteria||[]),...(r.market_criteria||[])];return <div key={r.id} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-white">{r.name}</p><p className="text-xs text-zinc-600 mt-1">{r.position||r.position_group||"Rol transversal"} · v{r.version||1}</p></div>{canEdit&&<button onClick={()=>onEdit(r)} className="text-xs text-zinc-500 hover:text-white">Editar</button>}</div><p className="text-xs text-zinc-400 mt-3 min-h-10">{r.description||"Sin descripción"}</p><div className="mt-3 flex flex-wrap gap-1">{criteria.slice(0,7).map((c,i)=><span key={`${c.key}-${i}`} className="px-2 py-1 rounded bg-zinc-950 text-[10px] text-zinc-500">{c.label}</span>)}{criteria.length>7&&<span className="px-2 py-1 text-[10px] text-zinc-600">+{criteria.length-7}</span>}</div></div>})}</div></div>}
function Empty({text}){return <div className="md:col-span-2 xl:col-span-3 rounded-xl border border-dashed border-zinc-800 p-10 text-center text-sm text-zinc-600">{text}</div>}
