import React, { useEffect, useMemo, useState } from "react";
import { ArrowRight, ClipboardPlus, Edit2, FileSearch, ListPlus, Loader2, ShieldCheck, X } from "lucide-react";
import { scoutingGateway, scoutingProspectDetail } from "@/lib/scoutingApi";
import { PIPELINE_STAGES, RECOMMENDATION_LABEL, STAGE_LABEL, fmtDate, fmtMoney, prospectAge } from "@/components/scouting/scoutingConstants";

function Badge({children,className=""}){return <span className={`inline-flex px-2 py-1 rounded-full text-[10px] font-semibold border ${className}`}>{children}</span>}
export default function ProspectDetailModal({prospectId,onClose,onEdit,onReport,onAssignment,onChanged}){
 const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[stage,setStage]=useState("");const[reason,setReason]=useState("");const[savingStage,setSavingStage]=useState(false);const[addingList,setAddingList]=useState("");
 async function load(){setLoading(true);setError("");try{const d=await scoutingProspectDetail(prospectId);setData(d);setStage(d.prospect?.pipeline_stage||"discovered")}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(prospectId)load()},[prospectId]);
 const prospect=data?.prospect;const reports=data?.reports||[];const assignments=data?.assignments||[];const events=data?.pipeline_events||[];const activeItems=data?.watchlist_items||[];const listIds=new Set(activeItems.map(i=>i.watchlist_id));
 const latestReport=reports[0];const avgFit=useMemo(()=>{const v=reports.map(r=>Number(r.fit_score)).filter(Number.isFinite);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):null},[reports]);
 async function changeStage(){if(!prospect||stage===prospect.pipeline_stage)return;setSavingStage(true);try{await scoutingGateway("change_stage",{prospect_id:prospect.id,to_stage:stage,reason:reason||"Actualización desde ficha de recruitment"});setReason("");await load();onChanged?.()}catch(e){setError(e.message)}finally{setSavingStage(false)}}
 async function addToList(watchlistId){setAddingList(watchlistId);try{await scoutingGateway("add_watchlist_item",{watchlist_id:watchlistId,prospect_id:prospect.id});await load();onChanged?.()}catch(e){setError(e.message)}finally{setAddingList("")}}
 if(loading)return <div className="fixed inset-0 z-[76] bg-black/80 flex items-center justify-center"><Loader2 className="animate-spin text-zinc-400"/></div>;
 return <div className="fixed inset-0 z-[76] bg-black/80 flex items-center justify-center p-3" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="w-full max-w-6xl max-h-[95vh] overflow-y-auto rounded-2xl border border-zinc-700 bg-zinc-950">
  <div className="sticky top-0 z-10 flex items-center justify-between p-5 border-b border-zinc-800 bg-zinc-950"><div className="flex items-center gap-4">{prospect?.photo_url?<img src={prospect.photo_url} alt="" className="w-14 h-14 rounded-full object-cover border border-zinc-700"/>:<div className="w-14 h-14 rounded-full bg-zinc-800 border border-zinc-700 flex items-center justify-center text-lg font-bold text-zinc-400">{prospect?.full_name?.slice(0,1)||"?"}</div>}<div><div className="flex items-center gap-2 flex-wrap"><h2 className="text-xl font-bold text-white">{prospect?.full_name}</h2><Badge className="border-blue-500/30 bg-blue-500/10 text-blue-300">{STAGE_LABEL[prospect?.pipeline_stage]||prospect?.pipeline_stage}</Badge></div><p className="text-sm text-zinc-500 mt-1">{prospect?.position||"Sin posición"} · {prospect?.current_club_name||"Sin club"}{prospectAge(prospect?.birth_date)!=null?` · ${prospectAge(prospect.birth_date)} años`:""}</p></div></div><div className="flex gap-1"><button onClick={()=>onEdit?.(prospect)} className="p-2 rounded-lg text-zinc-400 hover:bg-zinc-800 hover:text-white" title="Editar"><Edit2 size={16}/></button><button onClick={onClose} className="p-2 text-zinc-500 hover:text-white"><X size={18}/></button></div></div>
  <div className="p-5 space-y-5">{error&&<div className="p-3 rounded-xl border border-red-500/30 bg-red-500/10 text-sm text-red-300">{error}</div>}
   <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[["Informes",reports.length],["Fit prom.",avgFit!=null?`${avgFit}%`:"—"],["Recomendación",latestReport?RECOMMENDATION_LABEL[latestReport.recommendation]:"Sin informe"],["Contrato",fmtDate(prospect?.contract_end_date)],["Valor",fmtMoney(prospect?.market_value_estimate,prospect?.market_value_currency)]].map(([l,v])=><div key={l} className="bg-zinc-900 border border-zinc-800 rounded-xl p-3"><p className="text-[10px] text-zinc-600 uppercase">{l}</p><p className="text-sm font-bold text-white mt-1 truncate">{v}</p></div>)}</div>
   <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-4"><section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center justify-between mb-3"><div><h3 className="text-sm font-bold text-white">Decisión y pipeline</h3><p className="text-xs text-zinc-500">Mover de etapa requiere una acción explícita y queda auditado.</p></div><ShieldCheck size={17} className="text-zinc-600"/></div><div className="grid sm:grid-cols-[1fr_1.5fr_auto] gap-2"><select value={stage} onChange={e=>setStage(e.target.value)} className="bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white">{PIPELINE_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo / decisión" className="bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white"/><button disabled={savingStage||stage===prospect?.pipeline_stage} onClick={changeStage} className="px-3 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold disabled:opacity-40 flex items-center gap-1">Mover <ArrowRight size={13}/></button></div><div className="mt-4 space-y-2 max-h-48 overflow-y-auto">{events.map(e=><div key={e.id} className="flex items-start justify-between gap-3 border-l-2 border-zinc-700 pl-3 py-1"><div><p className="text-xs text-zinc-300">{e.from_stage?`${STAGE_LABEL[e.from_stage]||e.from_stage} → `:""}<b>{STAGE_LABEL[e.to_stage]||e.to_stage}</b></p><p className="text-[11px] text-zinc-600">{e.reason||"Cambio de etapa"}{e.actor_name?` · ${e.actor_name}`:""}</p></div><span className="text-[10px] text-zinc-600 shrink-0">{fmtDate(e.created_at)}</span></div>)}{!events.length&&<p className="text-xs text-zinc-600">Sin movimientos registrados.</p>}</div></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><h3 className="text-sm font-bold text-white mb-3">Mercado</h3><div className="space-y-2 text-xs"><Info label="Club" value={prospect?.current_club_name}/><Info label="Competición" value={prospect?.current_competition}/><Info label="Nacionalidad" value={prospect?.nationality}/><Info label="Disponibilidad" value={prospect?.availability_status}/><Info label="Fuente" value={prospect?.availability_source}/><Info label="Agente" value={prospect?.agent_name}/><Info label="Contacto" value={prospect?.agent_contact}/></div></section></div>
   <div className="flex gap-2 flex-wrap"><button onClick={()=>onReport?.(prospect.id)} className="px-3 py-2 rounded-lg bg-emerald-500 text-zinc-950 text-sm font-semibold flex items-center gap-1.5"><FileSearch size={14}/> Nuevo informe</button><button onClick={()=>onAssignment?.(prospect.id)} className="px-3 py-2 rounded-lg bg-zinc-800 text-zinc-200 text-sm font-semibold flex items-center gap-1.5"><ClipboardPlus size={14}/> Asignar observación</button></div>
   <section><h3 className="text-sm font-bold text-white mb-3">Watchlists</h3><div className="flex flex-wrap gap-2">{(data?.watchlists||[]).map(w=><button key={w.id} disabled={listIds.has(w.id)||addingList===w.id} onClick={()=>addToList(w.id)} className={`px-3 py-1.5 rounded-lg border text-xs flex items-center gap-1.5 ${listIds.has(w.id)?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":"border-zinc-800 bg-zinc-900 text-zinc-400 hover:text-white"}`}><ListPlus size={12}/>{listIds.has(w.id)?"En ":"Agregar a "}{w.name}</button>)}</div></section>
   <section><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-bold text-white">Informes</h3><span className="text-xs text-zinc-600">{reports.length} observaciones</span></div><div className="space-y-2">{reports.map(r=><div key={r.id} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Badge className="border-zinc-700 text-zinc-300">{r.report_type}</Badge><Badge className="border-emerald-500/20 bg-emerald-500/5 text-emerald-300">{RECOMMENDATION_LABEL[r.recommendation]||r.recommendation}</Badge></div><p className="text-sm text-white mt-2">{r.summary||"Sin resumen"}</p><p className="text-[11px] text-zinc-600 mt-2">{r.author_name} · {fmtDate(r.observation_date)} · confianza {r.confidence_score??"—"}%</p></div>{r.fit_score!=null&&<div className="text-right shrink-0"><p className="text-xl font-bold text-white">{Math.round(r.fit_score)}%</p><p className="text-[10px] text-zinc-600">fit</p></div>}</div>{r.strengths?.length>0&&<div className="mt-3 flex gap-1 flex-wrap">{r.strengths.slice(0,5).map((x,i)=><span key={i} className="px-2 py-1 rounded bg-emerald-500/10 text-emerald-300 text-[10px]">{x}</span>)}</div>}{r.risks?.length>0&&<div className="mt-2 flex gap-1 flex-wrap">{r.risks.slice(0,5).map((x,i)=><span key={i} className="px-2 py-1 rounded bg-red-500/10 text-red-300 text-[10px]">{x}</span>)}</div>}</div>)}{!reports.length&&<div className="p-8 border border-dashed border-zinc-800 rounded-xl text-center text-sm text-zinc-600">Todavía no hay informes. El prospecto está en la base, pero aún no existe evidencia de scouting.</div>}</div></section>
   {assignments.length>0&&<section><h3 className="text-sm font-bold text-white mb-3">Asignaciones</h3><div className="grid md:grid-cols-2 gap-2">{assignments.map(a=><div key={a.id} className="rounded-lg border border-zinc-800 bg-zinc-900 p-3"><div className="flex items-center justify-between"><p className="text-xs text-white font-semibold">{a.assigned_to_name||"Responsable"}</p><Badge className="border-zinc-700 text-zinc-400">{a.status}</Badge></div><p className="text-[11px] text-zinc-500 mt-1">{a.assignment_type} · vence {fmtDate(a.due_date)}</p>{a.instructions&&<p className="text-xs text-zinc-400 mt-2">{a.instructions}</p>}</div>)}</div></section>}
  </div>
 </div></div>
}
function Info({label,value}){return <div className="flex items-start justify-between gap-3 border-b border-zinc-800/60 pb-2"><span className="text-zinc-600">{label}</span><span className="text-zinc-300 text-right">{value||"—"}</span></div>}
