import React, { useState } from "react";
import { Target, X } from "lucide-react";
import { scoutingGateway } from "@/lib/scoutingApi";

const input = "w-full bg-zinc-900 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-zinc-500";
function Field({ label, children }) { return <div><label className="text-[11px] text-zinc-500 block mb-1.5">{label}</label>{children}</div>; }

export default function RecruitmentNeedModal({ need, squads = [], players = [], roleProfiles = [], staff = [], onClose, onSaved }) {
  const [form, setForm] = useState(() => ({
    title: need?.title || "", squad_id: need?.squad_id || "", position: need?.position || "", role_profile_id: need?.role_profile_id || "",
    priority: need?.priority || "medium", time_horizon: need?.time_horizon || "next_window", reason: need?.reason || "", current_player_id: need?.current_player_id || "",
    budget_min: need?.budget_min ?? "", budget_max: need?.budget_max ?? "", budget_currency: need?.budget_currency || "USD", target_date: need?.target_date || "",
    owner_user_id: need?.owner_user_id || "", notes: need?.notes || "", status: need?.status || "open",
  }));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const isEdit = !!need?.id;
  function setF(k,v){setForm((f)=>({...f,[k]:v}));}
  async function save(e){e.preventDefault();setError("");if(!form.title.trim()){setError("Definí qué necesita incorporar el club.");return;}setSaving(true);try{const squad=squads.find((s)=>s.id===form.squad_id);const owner=staff.find((s)=>s.id===form.owner_user_id);const payload={...form,squad_name:squad?.name||"",owner_name:owner?.name||"",budget_min:form.budget_min===""?null:Number(form.budget_min),budget_max:form.budget_max===""?null:Number(form.budget_max)};const data=isEdit?await scoutingGateway("update_need",{need_id:need.id,...payload}):await scoutingGateway("create_need",payload);onSaved?.(data.need);onClose?.();}catch(err){setError(err.message);}finally{setSaving(false);}}
  return <div className="fixed inset-0 z-[75] bg-black/80 flex items-center justify-center p-3" onClick={onClose}><form onSubmit={save} onClick={(e)=>e.stopPropagation()} className="w-full max-w-3xl max-h-[94vh] overflow-y-auto rounded-2xl bg-zinc-950 border border-zinc-700">
    <div className="flex items-center justify-between p-5 border-b border-zinc-800"><div className="flex items-center gap-3"><Target className="text-amber-400" size={20}/><div><h2 className="text-lg font-bold text-white">{isEdit?"Editar necesidad":"Nueva necesidad de recruitment"}</h2><p className="text-xs text-zinc-500">Primero definimos el problema; después buscamos jugadores.</p></div></div><button type="button" onClick={onClose} className="text-zinc-500 hover:text-white"><X size={18}/></button></div>
    <div className="p-5 space-y-5">{error&&<div className="p-3 rounded-xl border border-red-500/30 bg-red-500/10 text-sm text-red-300">{error}</div>}
      <div className="grid sm:grid-cols-2 gap-3"><Field label="Necesidad *"><input value={form.title} onChange={(e)=>setF("title",e.target.value)} placeholder="Ej. Central zurdo U23" className={input}/></Field><Field label="Plantel objetivo"><select value={form.squad_id} onChange={(e)=>setF("squad_id",e.target.value)} className={input}><option value="">Institucional / sin plantel</option>{squads.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Posición"><input value={form.position} onChange={(e)=>setF("position",e.target.value)} placeholder="Defensor central" className={input}/></Field><Field label="Perfil de rol"><select value={form.role_profile_id} onChange={(e)=>setF("role_profile_id",e.target.value)} className={input}><option value="">Sin perfil específico</option>{roleProfiles.map((r)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Prioridad"><select value={form.priority} onChange={(e)=>setF("priority",e.target.value)} className={input}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></select></Field><Field label="Horizonte"><select value={form.time_horizon} onChange={(e)=>setF("time_horizon",e.target.value)} className={input}><option value="current_window">Mercado actual</option><option value="next_window">Próximo mercado</option><option value="6_months">6 meses</option><option value="12_months">12 meses</option><option value="24_months">24 meses</option></select></Field><Field label="Jugador interno de referencia"><select value={form.current_player_id} onChange={(e)=>setF("current_player_id",e.target.value)} className={input}><option value="">Ninguno</option>{players.map((p)=><option key={p.id} value={p.id}>{p.full_name} · {p.position||"—"}</option>)}</select></Field><Field label="Responsable"><select value={form.owner_user_id} onChange={(e)=>setF("owner_user_id",e.target.value)} className={input}><option value="">Sin asignar</option>{staff.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div>
      <Field label="Motivo deportivo"><textarea rows={3} value={form.reason} onChange={(e)=>setF("reason",e.target.value)} className={`${input} resize-none`} placeholder="Reemplazo probable, falta de profundidad, necesidad de perfil..."/></Field>
      <div className="grid sm:grid-cols-3 gap-3"><Field label="Presupuesto mínimo"><input type="number" value={form.budget_min} onChange={(e)=>setF("budget_min",e.target.value)} className={input}/></Field><Field label="Presupuesto máximo"><input type="number" value={form.budget_max} onChange={(e)=>setF("budget_max",e.target.value)} className={input}/></Field><Field label="Moneda"><select value={form.budget_currency} onChange={(e)=>setF("budget_currency",e.target.value)} className={input}><option>USD</option><option>EUR</option><option>ARS</option></select></Field></div>
      <div className="grid sm:grid-cols-2 gap-3"><Field label="Fecha objetivo"><input type="date" value={form.target_date} onChange={(e)=>setF("target_date",e.target.value)} className={input}/></Field>{isEdit&&<Field label="Estado"><select value={form.status} onChange={(e)=>setF("status",e.target.value)} className={input}><option value="open">Abierta</option><option value="monitoring">En seguimiento</option><option value="shortlist_ready">Shortlist lista</option><option value="negotiation">Negociación</option><option value="filled">Cubierta</option><option value="cancelled">Cancelada</option></select></Field>}</div>
      <Field label="Notas"><textarea rows={2} value={form.notes} onChange={(e)=>setF("notes",e.target.value)} className={`${input} resize-none`}/></Field>
      <div className="flex justify-end gap-2 border-t border-zinc-800 pt-4"><button type="button" onClick={onClose} className="px-4 py-2 text-sm text-zinc-300 border border-zinc-700 rounded-lg">Cancelar</button><button disabled={saving} className="px-4 py-2 bg-white text-zinc-950 rounded-lg text-sm font-semibold disabled:opacity-50">{saving?"Guardando…":isEdit?"Guardar":"Crear necesidad"}</button></div>
    </div>
  </form></div>;
}
