import React, { useMemo, useState } from "react";
import { CalendarCheck, CheckCircle2, Plus } from "lucide-react";
import { scoutingGateway } from "@/lib/scoutingApi";
import { PIPELINE_STAGES, fmtDate } from "./scoutingConstants";

const DECISIONS = [
  ["advance","Avanzar"],["hold","Mantener"],["discard","Descartar"],["request_more_info","Pedir más información"],["market_check","Chequear mercado"],["medical_check","Chequeo médico"],["negotiation","Negociación"],
];

export default function RecruitmentMeetingsTab({ meetings, decisions, prospects, needs, staff, squads, canCreate, canEdit, onChanged }) {
  const [selectedId, setSelectedId] = useState(meetings[0]?.id || "");
  const [showNew, setShowNew] = useState(false);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ title:"", meeting_date:new Date().toISOString().slice(0,10), meeting_time:"", squad_id:"", status:"open", agenda:"", participant_user_ids:[], participant_names:[] });
  const [decisionForm, setDecisionForm] = useState({ prospect_id:"", recruitment_need_id:"", decision:"hold", rationale:"", owner_user_id:"", owner_name:"", due_date:"", target_stage:"", apply_pipeline_change:false });
  const selected = meetings.find((m)=>m.id===selectedId) || meetings[0] || null;
  const ownDecisions = selected ? decisions.filter((d)=>d.meeting_id===selected.id) : [];
  const prospectMap = useMemo(()=>new Map(prospects.map((p)=>[p.id,p])),[prospects]);
  const needMap = useMemo(()=>new Map(needs.map((n)=>[n.id,n])),[needs]);

  async function createMeeting(e){e.preventDefault();setSaving(true);setError("");try{const squad=squads.find(s=>s.id===form.squad_id);const res=await scoutingGateway("create_meeting",{...form,squad_name:squad?.name,season_id:squad?.season});setSelectedId(res.meeting.id);setShowNew(false);await onChanged?.()}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function recordDecision(e){e.preventDefault();if(!selected)return;setSaving(true);setError("");try{const owner=staff.find(s=>s.id===decisionForm.owner_user_id);await scoutingGateway("record_meeting_decision",{meeting_id:selected.id,...decisionForm,owner_name:owner?.name||decisionForm.owner_name});setDecisionForm({ prospect_id:"", recruitment_need_id:"", decision:"hold", rationale:"", owner_user_id:"", owner_name:"", due_date:"", target_stage:"", apply_pipeline_change:false });await onChanged?.()}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function closeMeeting(){if(!selected)return;try{await scoutingGateway("update_meeting",{meeting_id:selected.id,status:"closed"});await onChanged?.()}catch(e){setError(e.message)}}

  function toggleParticipant(user){const exists=form.participant_user_ids.includes(user.id);setForm((f)=>({...f,participant_user_ids:exists?f.participant_user_ids.filter(id=>id!==user.id):[...f.participant_user_ids,user.id],participant_names:exists?f.participant_names.filter(n=>n!==user.name):[...f.participant_names,user.name]}))}

  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3 flex-wrap"><div><h3 className="text-sm font-bold text-white flex items-center gap-2"><CalendarCheck size={16} className="text-violet-400"/> Recruitment Meetings</h3><p className="text-xs text-zinc-600 mt-1">La reunión deja agenda, decisiones, responsables y evidencia. El pipeline sólo cambia con confirmación explícita.</p></div>{canCreate&&<button onClick={()=>setShowNew(v=>!v)} className="px-3 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold flex items-center gap-1"><Plus size={13}/> Nueva reunión</button>}</div>
    {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-300">{error}</div>}
    {showNew&&<form onSubmit={createMeeting} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4 space-y-3"><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3"><Field label="Título"><input required className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Reunión mercado de pases"/></Field><Field label="Fecha"><input required type="date" className="input" value={form.meeting_date} onChange={e=>setForm({...form,meeting_date:e.target.value})}/></Field><Field label="Hora"><input type="time" className="input" value={form.meeting_time} onChange={e=>setForm({...form,meeting_time:e.target.value})}/></Field><Field label="Plantel"><select className="input" value={form.squad_id} onChange={e=>setForm({...form,squad_id:e.target.value})}><option value="">Institucional</option>{squads.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div><Field label="Agenda"><textarea className="input min-h-20" value={form.agenda} onChange={e=>setForm({...form,agenda:e.target.value})} placeholder="Necesidades abiertas, candidatos prioritarios, información pendiente…"/></Field><div><p className="text-[10px] text-zinc-500 mb-2">Participantes</p><div className="flex flex-wrap gap-1.5">{staff.map(s=><button key={s.id} type="button" onClick={()=>toggleParticipant(s)} className={`px-2.5 py-1 rounded-full border text-[10px] ${form.participant_user_ids.includes(s.id)?"border-violet-500/40 bg-violet-500/10 text-violet-300":"border-zinc-700 text-zinc-500"}`}>{s.name}</button>)}</div></div><div className="flex justify-end"><button disabled={saving} className="px-4 py-2 rounded-lg bg-violet-400 text-zinc-950 text-xs font-bold">Crear reunión</button></div></form>}
    <div className="grid lg:grid-cols-[300px_1fr] gap-4">
      <div className="space-y-2">{meetings.map(m=><button key={m.id} onClick={()=>setSelectedId(m.id)} className={`w-full text-left rounded-xl border p-3 ${selected?.id===m.id?"border-violet-500/30 bg-violet-500/[0.06]":"border-zinc-800 bg-zinc-900"}`}><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold text-white">{m.title}</p><span className={`text-[9px] px-2 py-0.5 rounded-full border ${m.status==="closed"?"border-emerald-500/30 text-emerald-300":"border-zinc-700 text-zinc-500"}`}>{m.status}</span></div><p className="text-[10px] text-zinc-600 mt-1">{fmtDate(m.meeting_date)} {m.meeting_time?`· ${m.meeting_time}`:""}</p><p className="text-[10px] text-zinc-600 mt-1">{(m.participant_names||[]).join(", ")||"Sin participantes"}</p></button>)}{!meetings.length&&<Empty text="Todavía no hay reuniones registradas."/>}</div>
      {selected&&<div className="space-y-3"><div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-bold text-white">{selected.title}</p><p className="text-xs text-zinc-600 mt-1">{fmtDate(selected.meeting_date)} · {selected.squad_name||"Institucional"}</p></div>{canEdit&&selected.status!=="closed"&&<button onClick={closeMeeting} className="text-xs text-zinc-500 hover:text-emerald-300 flex items-center gap-1"><CheckCircle2 size={13}/> Cerrar reunión</button>}</div>{selected.agenda&&<div className="mt-3 rounded-lg bg-zinc-950 p-3"><p className="text-[9px] uppercase tracking-wider text-zinc-600">Agenda</p><p className="text-xs text-zinc-400 whitespace-pre-wrap mt-1">{selected.agenda}</p></div>}</div>
        {canEdit&&selected.status!=="closed"&&<form onSubmit={recordDecision} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4 space-y-3"><p className="text-xs font-bold text-white">Registrar decisión</p><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3"><Field label="Prospecto"><select required className="input" value={decisionForm.prospect_id} onChange={e=>setDecisionForm({...decisionForm,prospect_id:e.target.value})}><option value="">Seleccionar…</option>{prospects.map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.current_club_name||"Sin club"}</option>)}</select></Field><Field label="Necesidad"><select className="input" value={decisionForm.recruitment_need_id} onChange={e=>setDecisionForm({...decisionForm,recruitment_need_id:e.target.value})}><option value="">Sin necesidad</option>{needs.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></Field><Field label="Decisión"><select className="input" value={decisionForm.decision} onChange={e=>setDecisionForm({...decisionForm,decision:e.target.value})}>{DECISIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Responsable"><select className="input" value={decisionForm.owner_user_id} onChange={e=>setDecisionForm({...decisionForm,owner_user_id:e.target.value})}><option value="">Sin responsable</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Vencimiento"><input type="date" className="input" value={decisionForm.due_date} onChange={e=>setDecisionForm({...decisionForm,due_date:e.target.value})}/></Field><Field label="Etapa propuesta"><select className="input" value={decisionForm.target_stage} onChange={e=>setDecisionForm({...decisionForm,target_stage:e.target.value})}><option value="">No proponer cambio</option>{PIPELINE_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></Field></div><Field label="Racional / decisión documentada"><textarea required className="input min-h-20" value={decisionForm.rationale} onChange={e=>setDecisionForm({...decisionForm,rationale:e.target.value})} placeholder="Qué se decidió y por qué…"/></Field><label className="flex items-start gap-2 rounded-lg border border-amber-500/20 bg-amber-500/[0.04] p-3"><input type="checkbox" checked={decisionForm.apply_pipeline_change} onChange={e=>setDecisionForm({...decisionForm,apply_pipeline_change:e.target.checked})} className="mt-0.5"/><span><span className="text-xs text-amber-300 font-semibold">Aplicar cambio de etapa al guardar</span><span className="text-[10px] text-zinc-600 block mt-0.5">Sólo se ejecutará si elegiste una etapa válida arriba. La decisión queda registrada aunque no cambies el pipeline.</span></span></label><div className="flex justify-end"><button disabled={saving} className="px-4 py-2 rounded-lg bg-white text-zinc-950 text-xs font-bold">Guardar decisión</button></div></form>}
        <div className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-hidden"><div className="p-3 border-b border-zinc-800"><p className="text-xs font-bold text-white">Historial de decisiones ({ownDecisions.length})</p></div><div className="divide-y divide-zinc-800">{ownDecisions.map(d=><div key={d.id} className="p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold text-white">{d.prospect_name||prospectMap.get(d.prospect_id)?.full_name||"Prospecto"}</p><p className="text-[10px] text-violet-300 mt-0.5">{decisionLabel(d.decision)}{d.pipeline_change_applied&&d.target_stage?` · pipeline → ${PIPELINE_STAGES.find(s=>s.id===d.target_stage)?.label||d.target_stage}`:""}</p></div><span className="text-[9px] text-zinc-600">{fmtDate(String(d.created_at||"").slice(0,10))}</span></div><p className="text-xs text-zinc-500 mt-2">{d.rationale}</p><div className="flex gap-3 mt-2 text-[9px] text-zinc-600">{d.recruitment_need_id&&<span>Necesidad: {needMap.get(d.recruitment_need_id)?.title||"—"}</span>}{d.owner_name&&<span>Responsable: {d.owner_name}</span>}{d.due_date&&<span>Vence: {fmtDate(d.due_date)}</span>}</div></div>)}{!ownDecisions.length&&<div className="p-8 text-center text-xs text-zinc-600">Sin decisiones registradas.</div>}</div></div>
      </div>}
    </div>
    <style>{`.input{width:100%;background:#09090b;border:1px solid #27272a;border-radius:.5rem;padding:.5rem .75rem;font-size:.75rem;color:white;outline:none}.input:focus{border-color:#52525b}`}</style>
  </div>;
}

function Field({label,children}){return <label className="block"><span className="text-[10px] text-zinc-500 block mb-1">{label}</span>{children}</label>}
function Empty({text}){return <div className="rounded-xl border border-dashed border-zinc-800 p-8 text-center text-xs text-zinc-600">{text}</div>}
function decisionLabel(v){return Object.fromEntries(DECISIONS)[v]||v}
