import React, { useState } from "react";
import { Plus, Trash2, X, SlidersHorizontal } from "lucide-react";
import { scoutingGateway } from "@/lib/scoutingApi";

const input="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-zinc-500";
const GROUPS=[{key:"technical_criteria",label:"Técnico"},{key:"tactical_criteria",label:"Táctico"},{key:"physical_criteria",label:"Físico"},{key:"mental_criteria",label:"Mental / competitivo"},{key:"market_criteria",label:"Mercado"}];
function slug(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")}
export default function RoleProfileModal({profile,onClose,onSaved}){
 const [form,setForm]=useState(()=>({name:profile?.name||"",position_group:profile?.position_group||"",position:profile?.position||"",description:profile?.description||"",tactical_model:profile?.tactical_model||"",age_min:profile?.age_min??"",age_max:profile?.age_max??"",preferred_foot:profile?.preferred_foot||"any",min_height_cm:profile?.min_height_cm??"",max_market_value:profile?.max_market_value??"",market_currency:profile?.market_currency||"USD",technical_criteria:profile?.technical_criteria||[],tactical_criteria:profile?.tactical_criteria||[],physical_criteria:profile?.physical_criteria||[],mental_criteria:profile?.mental_criteria||[],market_criteria:profile?.market_criteria||[]}));
 const [saving,setSaving]=useState(false);const[error,setError]=useState("");const isEdit=!!profile?.id;
 function setF(k,v){setForm(f=>({...f,[k]:v}))}
 function add(group){setF(group,[...(form[group]||[]),{key:"",label:"",weight:10,description:""}])}
 function update(group,index,key,value){setF(group,(form[group]||[]).map((row,i)=>i===index?{...row,[key]:value,key:key==="label"&&!row.key?slug(value):row.key}:row))}
 function remove(group,index){setF(group,(form[group]||[]).filter((_,i)=>i!==index))}
 async function save(e){e.preventDefault();setError("");if(!form.name.trim()){setError("Ingresá el nombre del rol.");return;}setSaving(true);try{const payload={...form,age_min:form.age_min===""?null:Number(form.age_min),age_max:form.age_max===""?null:Number(form.age_max),min_height_cm:form.min_height_cm===""?null:Number(form.min_height_cm),max_market_value:form.max_market_value===""?null:Number(form.max_market_value)};const data=isEdit?await scoutingGateway("update_role_profile",{role_profile_id:profile.id,...payload}):await scoutingGateway("create_role_profile",payload);onSaved?.(data.role_profile);onClose?.()}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-[82] bg-black/85 flex items-center justify-center p-3" onClick={onClose}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="w-full max-w-5xl max-h-[95vh] overflow-y-auto rounded-2xl border border-zinc-700 bg-zinc-950"><div className="sticky top-0 z-10 flex items-center justify-between p-5 border-b border-zinc-800 bg-zinc-950"><div className="flex items-center gap-3"><SlidersHorizontal size={20} className="text-cyan-400"/><div><h2 className="text-lg font-bold text-white">{isEdit?"Editar perfil de rol":"Nuevo perfil de rol"}</h2><p className="text-xs text-zinc-500">El club define qué significa “encajar” en cada función.</p></div></div><button type="button" onClick={onClose} className="text-zinc-500 hover:text-white"><X size={18}/></button></div><div className="p-5 space-y-5">{error&&<div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-sm text-red-300">{error}</div>}
  <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><div><label className="text-[11px] text-zinc-500 block mb-1">Nombre *</label><input value={form.name} onChange={e=>setF("name",e.target.value)} placeholder="Central constructor" className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Grupo</label><input value={form.position_group} onChange={e=>setF("position_group",e.target.value)} placeholder="Defensores" className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Posición</label><input value={form.position} onChange={e=>setF("position",e.target.value)} className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Pie preferido</label><select value={form.preferred_foot} onChange={e=>setF("preferred_foot",e.target.value)} className={input}><option value="any">Cualquiera</option><option value="right">Derecho</option><option value="left">Izquierdo</option><option value="both">Ambos</option></select></div></div>
  <div><label className="text-[11px] text-zinc-500 block mb-1">Descripción</label><textarea rows={2} value={form.description} onChange={e=>setF("description",e.target.value)} className={`${input} resize-none`}/></div>
  {GROUPS.map(g=><section key={g.key} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center justify-between mb-3"><div><h3 className="text-sm font-bold text-white">{g.label}</h3><p className="text-[10px] text-zinc-600">Peso relativo documentado; no es un algoritmo oculto.</p></div><button type="button" onClick={()=>add(g.key)} className="px-2.5 py-1.5 rounded-lg bg-zinc-800 text-xs text-zinc-300 flex items-center gap-1"><Plus size={12}/> Criterio</button></div><div className="space-y-2">{(form[g.key]||[]).map((row,i)=><div key={i} className="grid grid-cols-[1fr_90px_36px] gap-2"><input value={row.label||""} onChange={e=>update(g.key,i,"label",e.target.value)} placeholder="Nombre del criterio" className={input}/><input type="number" min="0" max="100" value={row.weight??10} onChange={e=>update(g.key,i,"weight",Number(e.target.value))} className={input}/><button type="button" onClick={()=>remove(g.key,i)} className="rounded-lg border border-zinc-800 text-zinc-600 hover:text-red-400"><Trash2 size={14} className="mx-auto"/></button></div>)}{!(form[g.key]||[]).length&&<p className="text-xs text-zinc-600">Sin criterios en esta dimensión.</p>}</div></section>)}
  <div className="grid sm:grid-cols-5 gap-3"><div><label className="text-[11px] text-zinc-500 block mb-1">Edad mín.</label><input type="number" value={form.age_min} onChange={e=>setF("age_min",e.target.value)} className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Edad máx.</label><input type="number" value={form.age_max} onChange={e=>setF("age_max",e.target.value)} className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Altura mín.</label><input type="number" value={form.min_height_cm} onChange={e=>setF("min_height_cm",e.target.value)} className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Valor máx.</label><input type="number" value={form.max_market_value} onChange={e=>setF("max_market_value",e.target.value)} className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Moneda</label><select value={form.market_currency} onChange={e=>setF("market_currency",e.target.value)} className={input}><option>USD</option><option>EUR</option><option>ARS</option></select></div></div>
  <div className="flex justify-end gap-2 border-t border-zinc-800 pt-4"><button type="button" onClick={onClose} className="px-4 py-2 rounded-lg border border-zinc-700 text-sm text-zinc-300">Cancelar</button><button disabled={saving} className="px-4 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold disabled:opacity-50">{saving?"Guardando…":isEdit?"Guardar versión":"Crear perfil"}</button></div>
 </div></form></div>
}
