import React, { useMemo, useState } from "react";
import { FileSearch, X } from "lucide-react";
import { scoutingGateway } from "@/lib/scoutingApi";

const input="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-zinc-500";
const CATEGORIES=[
 {key:"technical",label:"Técnico",criteria:"technical_criteria"},{key:"tactical",label:"Táctico",criteria:"tactical_criteria"},{key:"physical",label:"Físico",criteria:"physical_criteria"},{key:"mental",label:"Mental / competitivo",criteria:"mental_criteria"},{key:"market",label:"Mercado",criteria:"market_criteria"},
];
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Argentina/Buenos_Aires"}).format(new Date())}
function lines(value){return String(value||"").split(/\n|,/).map(x=>x.trim()).filter(Boolean)}
function Field({label,children}){return <div><label className="text-[11px] text-zinc-500 block mb-1.5">{label}</label>{children}</div>}

export default function ScoutingReportModal({prospectId,prospects=[],needs=[],assignments=[],roleProfiles=[],onClose,onSaved}){
 const prospect=prospects.find(p=>p.id===prospectId);
 const defaultRole=roleProfiles.find(r=>(prospect?.role_profile_ids||[]).includes(r.id))?.id||"";
 const [form,setForm]=useState({prospect_id:prospectId||"",recruitment_need_id:"",assignment_id:"",report_type:"video",observation_date:today(),match_date:"",match_label:"",competition:"",opponent:"",minutes_observed:"",role_profile_id:defaultRole,recommendation:"monitor",confidence_score:60,sample_quality:"medium",summary:"",technical_note:"",tactical_note:"",physical_note:"",mental_note:"",market_note:"",strengths:"",risks:"",questions_to_verify:"",technical_scores:{},tactical_scores:{},physical_scores:{},mental_scores:{},market_scores:{}});
 const [saving,setSaving]=useState(false);const[error,setError]=useState("");
 function setF(k,v){setForm(f=>({...f,[k]:v}))}
 const role=roleProfiles.find(r=>r.id===form.role_profile_id);
 const localFit=useMemo(()=>{const vals=[];CATEGORIES.forEach(c=>Object.values(form[`${c.key}_scores`]||{}).forEach(v=>{const n=Number(v);if(Number.isFinite(n)&&n>=0&&n<=10)vals.push(n)}));return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10):null},[form]);
 function setScore(category,key,value){setForm(f=>({...f,[`${category}_scores`]:{...f[`${category}_scores`],[key]:value}}))}
 async function save(e){e.preventDefault();setError("");if(!form.prospect_id){setError("Seleccioná un prospecto.");return;}setSaving(true);try{const payload={...form,minutes_observed:form.minutes_observed===""?null:Number(form.minutes_observed),confidence_score:Number(form.confidence_score),role_profile_name:role?.name||"",strengths:lines(form.strengths),risks:lines(form.risks),questions_to_verify:lines(form.questions_to_verify)};const data=await scoutingGateway("create_report",payload);onSaved?.(data.report);onClose?.();}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-[80] bg-black/85 flex items-center justify-center p-3" onClick={onClose}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="w-full max-w-6xl max-h-[95vh] overflow-y-auto rounded-2xl bg-zinc-950 border border-zinc-700">
  <div className="sticky top-0 z-10 flex items-center justify-between p-5 border-b border-zinc-800 bg-zinc-950"><div className="flex items-center gap-3"><FileSearch size={20} className="text-emerald-400"/><div><h2 className="text-lg font-bold text-white">Nuevo informe de scouting</h2><p className="text-xs text-zinc-500">Criterios + evidencia + recomendación humana. El fit no decide por el scout.</p></div></div><div className="flex items-center gap-3">{localFit!==null&&<div className="text-right"><p className="text-lg font-bold text-white">{localFit}%</p><p className="text-[10px] text-zinc-600">fit descriptivo</p></div>}<button type="button" onClick={onClose} className="text-zinc-500 hover:text-white"><X size={18}/></button></div></div>
  <div className="p-5 space-y-6">{error&&<div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-sm text-red-300">{error}</div>}
   <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Field label="Prospecto"><select value={form.prospect_id} onChange={e=>setF("prospect_id",e.target.value)} className={input}><option value="">Seleccionar...</option>{prospects.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></Field><Field label="Tipo"><select value={form.report_type} onChange={e=>setF("report_type",e.target.value)} className={input}><option value="video">Video</option><option value="live">En vivo</option><option value="data">Datos</option><option value="background">Background</option><option value="composite">Compuesto</option></select></Field><Field label="Fecha de observación"><input type="date" value={form.observation_date} onChange={e=>setF("observation_date",e.target.value)} className={input}/></Field><Field label="Perfil de rol"><select value={form.role_profile_id} onChange={e=>setF("role_profile_id",e.target.value)} className={input}><option value="">Evaluación general</option>{roleProfiles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Necesidad"><select value={form.recruitment_need_id} onChange={e=>setF("recruitment_need_id",e.target.value)} className={input}><option value="">Sin necesidad específica</option>{needs.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></Field><Field label="Asignación"><select value={form.assignment_id} onChange={e=>setF("assignment_id",e.target.value)} className={input}><option value="">Sin asignación</option>{assignments.filter(a=>a.prospect_id===form.prospect_id&&a.status!=="cancelled").map(a=><option key={a.id} value={a.id}>{a.assignment_type} · {a.match_label||a.due_date||"asignación"}</option>)}</select></Field><Field label="Partido"><input value={form.match_label} onChange={e=>setF("match_label",e.target.value)} placeholder="Local vs Visitante" className={input}/></Field><Field label="Minutos observados"><input type="number" min="0" value={form.minutes_observed} onChange={e=>setF("minutes_observed",e.target.value)} className={input}/></Field></div>
   {role?<section className="space-y-4"><div><h3 className="text-sm font-bold text-white">Criterios — {role.name}</h3><p className="text-xs text-zinc-500 mt-1">Escala 0–10. PerformancePitch muestra el promedio como referencia, pero la recomendación se registra por separado.</p></div>{CATEGORIES.map(c=>{const criteria=role[c.criteria]||[];if(!criteria.length)return null;return <div key={c.key} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><h4 className="text-xs font-bold text-zinc-300 uppercase tracking-wider mb-3">{c.label}</h4><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{criteria.map(cr=><div key={cr.key} className="rounded-lg bg-zinc-950 border border-zinc-800 p-3"><div className="flex items-center justify-between gap-2 mb-2"><span className="text-xs text-zinc-300 font-medium">{cr.label}</span>{cr.weight!=null&&<span className="text-[10px] text-zinc-600">peso {cr.weight}</span>}</div><input type="number" min="0" max="10" step="0.5" value={form[`${c.key}_scores`]?.[cr.key]??""} onChange={e=>setScore(c.key,cr.key,e.target.value)} className={input}/></div>)}</div><textarea rows={2} value={form[`${c.key}_note`]||""} onChange={e=>setF(`${c.key}_note`,e.target.value)} placeholder={`Observación ${c.label.toLowerCase()}...`} className={`${input} resize-none mt-3`}/></div>})}</section>:<div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs text-amber-200">Sin perfil de rol: podés hacer un informe general, pero no habrá criterios estandarizados para comparar scouts.</div>}
   <div className="grid lg:grid-cols-2 gap-4"><Field label="Resumen del scout"><textarea rows={5} value={form.summary} onChange={e=>setF("summary",e.target.value)} className={`${input} resize-none`} placeholder="Qué jugador vimos, en qué contexto y cuál es la lectura principal..."/></Field><div className="grid gap-3"><Field label="Fortalezas (una por línea)"><textarea rows={3} value={form.strengths} onChange={e=>setF("strengths",e.target.value)} className={`${input} resize-none`}/></Field><Field label="Riesgos / dudas (una por línea)"><textarea rows={3} value={form.risks} onChange={e=>setF("risks",e.target.value)} className={`${input} resize-none`}/></Field></div></div>
   <div className="grid sm:grid-cols-3 gap-3"><Field label="Recomendación humana"><select value={form.recommendation} onChange={e=>setF("recommendation",e.target.value)} className={input}><option value="strong_recommend">Recomendar fuerte</option><option value="recommend">Recomendar</option><option value="monitor">Seguir observando</option><option value="doubt">Dudas</option><option value="do_not_recommend">No recomendar</option></select></Field><Field label="Confianza del informe"><div className="flex items-center gap-3"><input type="range" min="0" max="100" step="5" value={form.confidence_score} onChange={e=>setF("confidence_score",e.target.value)} className="flex-1"/><span className="text-sm text-white w-10 text-right">{form.confidence_score}%</span></div></Field><Field label="Calidad de muestra"><select value={form.sample_quality} onChange={e=>setF("sample_quality",e.target.value)} className={input}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></Field></div>
   <Field label="Qué falta verificar"><textarea rows={2} value={form.questions_to_verify} onChange={e=>setF("questions_to_verify",e.target.value)} className={`${input} resize-none`} placeholder="Una pregunta por línea"/></Field>
   <div className="flex justify-end gap-2 border-t border-zinc-800 pt-4"><button type="button" onClick={onClose} className="px-4 py-2 rounded-lg border border-zinc-700 text-sm text-zinc-300">Cancelar</button><button disabled={saving} className="px-4 py-2 rounded-lg bg-emerald-500 text-zinc-950 text-sm font-bold disabled:opacity-50">{saving?"Guardando…":"Guardar informe"}</button></div>
  </div>
 </form></div>
}
