import React, { useState } from "react";
import { ListPlus, X } from "lucide-react";
import { scoutingGateway } from "@/lib/scoutingApi";
const input="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-zinc-500";
export default function WatchlistModal({needs=[],squads=[],onClose,onSaved}){
 const[form,setForm]=useState({name:"",description:"",watchlist_type:"custom",recruitment_need_id:"",squad_id:"",visibility:"department"});const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 function setF(k,v){setForm(f=>({...f,[k]:v}))}
 async function save(e){e.preventDefault();setError("");if(!form.name.trim()){setError("Ingresá un nombre para la lista.");return;}setSaving(true);try{const data=await scoutingGateway("create_watchlist",form);onSaved?.(data.watchlist);onClose?.()}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-[84] bg-black/80 flex items-center justify-center p-3" onClick={onClose}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="w-full max-w-lg rounded-2xl border border-zinc-700 bg-zinc-950"><div className="flex items-center justify-between p-5 border-b border-zinc-800"><div className="flex items-center gap-3"><ListPlus size={19} className="text-fuchsia-400"/><div><h2 className="text-lg font-bold text-white">Nueva watchlist</h2><p className="text-xs text-zinc-500">Organizá mercado, seguimiento y decisión.</p></div></div><button type="button" onClick={onClose} className="text-zinc-500 hover:text-white"><X size={18}/></button></div><div className="p-5 space-y-4">{error&&<div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-sm text-red-300">{error}</div>}<div><label className="text-[11px] text-zinc-500 block mb-1">Nombre *</label><input value={form.name} onChange={e=>setF("name",e.target.value)} className={input}/></div><div><label className="text-[11px] text-zinc-500 block mb-1">Tipo</label><select value={form.watchlist_type} onChange={e=>setF("watchlist_type",e.target.value)} className={input}><option value="longlist">Longlist</option><option value="shortlist">Shortlist</option><option value="shadow_squad">Shadow Squad</option><option value="monitoring">Seguimiento</option><option value="custom">Personalizada</option></select></div><div><label className="text-[11px] text-zinc-500 block mb-1">Descripción</label><textarea rows={2} value={form.description} onChange={e=>setF("description",e.target.value)} className={`${input} resize-none`}/></div><div className="grid grid-cols-2 gap-3"><div><label className="text-[11px] text-zinc-500 block mb-1">Necesidad</label><select value={form.recruitment_need_id} onChange={e=>setF("recruitment_need_id",e.target.value)} className={input}><option value="">General</option>{needs.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></div><div><label className="text-[11px] text-zinc-500 block mb-1">Plantel</label><select value={form.squad_id} onChange={e=>setF("squad_id",e.target.value)} className={input}><option value="">Institucional</option>{squads.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div><div><label className="text-[11px] text-zinc-500 block mb-1">Visibilidad</label><select value={form.visibility} onChange={e=>setF("visibility",e.target.value)} className={input}><option value="private">Privada</option><option value="department">Departamento</option><option value="club">Club</option></select></div><div className="flex justify-end gap-2 border-t border-zinc-800 pt-4"><button type="button" onClick={onClose} className="px-4 py-2 rounded-lg border border-zinc-700 text-sm text-zinc-300">Cancelar</button><button disabled={saving} className="px-4 py-2 rounded-lg bg-white text-zinc-950 text-sm font-semibold disabled:opacity-50">{saving?"Creando…":"Crear lista"}</button></div></div></form></div>
}
